/////////////////////////////////////////////////
//
// MUSE Header for .WL6
// Created Tue Jul 14 15:04:53 1992
//
/////////////////////////////////////////////////

#ifndef __AUDIOWL6_H_
#define __AUDIOWL6_H_

//
// Sound names & indexes
//
enum soundnames
{
    HITWALLSND,
    SELECTWPNSND,
    SELECTITEMSND,
    HEARTBEATSND,
    MOVEGUN2SND,
    MOVEGUN1SND,
    NOWAYSND,
    NAZIHITPLAYERSND,
    SCHABBSTHROWSND,
    PLAYERDEATHSND,
    DOGDEATHSND,
    ATKGATLINGSND,
    GETKEYSND,
    NOITEMSND,
    WALK1SND,
    WALK2SND,
    TAKEDAMAGESND,
    GAMEOVERSND,
    OPENDOORSND,
    CLOSEDOORSND,
    DONOTHINGSND,
    HALTSND,
    DEATHSCREAM2SND,
    ATKKNIFESND,
    ATKPISTOLSND,
    DEATHSCREAM3SND,
    ATKMACHINEGUNSND,
    HITENEMYSND,
    SHOOTDOORSND,
    DEATHSCREAM1SND,
    GETMACHINESND,
    GETAMMOSND,
    SHOOTSND,
    HEALTH1SND,
    HEALTH2SND,
    BONUS1SND,
    BONUS2SND,
    BONUS3SND,
    GETGATLINGSND,
    ESCPRESSEDSND,
    LEVELDONESND,
    DOGBARKSND,
    ENDBONUS1SND,
    ENDBONUS2SND,
    BONUS1UPSND,
    BONUS4SND,
    PUSHWALLSND,
    NOBONUSSND,
    PERCENT100SND,
    BOSSACTIVESND,
    MUTTISND,
    SCHUTZADSND,
    AHHHGSND,
    DIESND,
    EVASND,
    GUTENTAGSND,
    LEBENSND,
    SCHEISTSND,
    NAZIFIRESND,
    BOSSFIRESND,
    SSFIRESND,
    SLURPIESND,
    TOT_HUNDSND,
    MEINGOTTSND,
    SCHABBSHASND,
    HITLERHASND,
    SPIONSND,
    NEINSOVASSND,
    DOGATTACKSND,
    FLAMETHROWERSND,
    MECHSTEPSND,
    GOOBSSND,
    YEAHSND,
#ifndef APOGEE_1_0
    DEATHSCREAM4SND,
    DEATHSCREAM5SND,
    DEATHSCREAM6SND,
    DEATHSCREAM7SND,
    DEATHSCREAM8SND,
    DEATHSCREAM9SND,
    DONNERSND,
    EINESND,
    ERLAUBENSND,
    KEINSND,
    MEINSND,
    ROSESND,
    MISSILEFIRESND,
    MISSILEHITSND,
#endif
    LASTSOUND
};

//
// Base offsets
//
#define STARTPCSOUNDS       0
#define STARTADLIBSOUNDS    LASTSOUND
#define STARTDIGISOUNDS     (2 * LASTSOUND)
#define STARTMUSIC          (3 * LASTSOUND)

//
// Music names & indexes
//
enum musicnames
{
    CORNER_MUS,
    DUNGEON_MUS,
    WARMARCH_MUS,
    GETTHEM_MUS,
    HEADACHE_MUS,
    HITLWLTZ_MUS,
    INTROCW3_MUS,
    NAZI_NOR_MUS,
    NAZI_OMI_MUS,
    POW_MUS,
    SALUTE_MUS,
    SEARCHN_MUS,
    SUSPENSE_MUS,
    VICTORS_MUS,
    WONDERIN_MUS,
    FUNKYOU_MUS,
    ENDLEVEL_MUS,
    GOINGAFT_MUS,
    PREGNANT_MUS,
    ULTIMATE_MUS,
    NAZI_RAP_MUS,
    ZEROHOUR_MUS,
    TWELFTH_MUS,
    ROSTER_MUS,
    URAHERO_MUS,
    VICMARCH_MUS,
    PACMAN_MUS,

    LASTMUSIC
};

#define NUMSOUNDS           LASTSOUND
#define NUMSNDCHUNKS        (STARTMUSIC + LASTMUSIC)

/////////////////////////////////////////////////
//
// Thanks for playing with MUSE!
//
/////////////////////////////////////////////////

#endif
