//////////////////////////////////////
//
// Graphics .H file for .SOD
// IGRAB-ed on Thu Oct 08 20:38:29 1992
//
//////////////////////////////////////

#ifndef __GFXV_SOD_H_
#define __GFXV_SOD_H_

enum graphicnums
{
    STRUCTPIC,

    STARTFONT,
    FONT1 = STARTFONT,
    FONT2,

    STARTPICS,
    C_BACKDROPPIC = STARTPICS,
    C_MOUSELBACKPIC,
    C_CURSOR1PIC,
    C_CURSOR2PIC,
    C_NOTSELECTEDPIC,
    C_SELECTEDPIC,
    C_CUSTOMIZEPIC,
    C_JOY1PIC,
    C_JOY2PIC,
    C_MOUSEPIC,
    C_JOYSTICKPIC,
    C_KEYBOARDPIC,
    C_CONTROLPIC,
    C_OPTIONSPIC,
    C_FXTITLEPIC,
    C_DIGITITLEPIC,
    C_MUSICTITLEPIC,
    C_HOWTOUGHPIC,
    C_BABYMODEPIC,
    C_EASYPIC,
    C_NORMALPIC,
    C_HARDPIC,
    C_DISKLOADING1PIC,
    C_DISKLOADING2PIC,
    C_LOADGAMEPIC,
    C_SAVEGAMEPIC,
    HIGHSCORESPIC,
    C_WONSPEARPIC,
#ifndef SPEARDEMO
    BJCOLLAPSE1PIC,
    BJCOLLAPSE2PIC,
    BJCOLLAPSE3PIC,
    BJCOLLAPSE4PIC,
    ENDPICPIC,
#endif
    L_GUYPIC,
    L_COLONPIC,
    L_NUM0PIC,
    L_NUM1PIC,
    L_NUM2PIC,
    L_NUM3PIC,
    L_NUM4PIC,
    L_NUM5PIC,
    L_NUM6PIC,
    L_NUM7PIC,
    L_NUM8PIC,
    L_NUM9PIC,
    L_PERCENTPIC,
    L_APIC,
    L_BPIC,
    L_CPIC,
    L_DPIC,
    L_EPIC,
    L_FPIC,
    L_GPIC,
    L_HPIC,
    L_IPIC,
    L_JPIC,
    L_KPIC,
    L_LPIC,
    L_MPIC,
    L_NPIC,
    L_OPIC,
    L_PPIC,
    L_QPIC,
    L_RPIC,
    L_SPIC,
    L_TPIC,
    L_UPIC,
    L_VPIC,
    L_WPIC,
    L_XPIC,
    L_YPIC,
    L_ZPIC,
    L_EXPOINTPIC,
    L_APOSTROPHEPIC,
    L_GUY2PIC,
    L_BJWINSPIC,
    TITLE1PIC,
    TITLE2PIC,
#ifndef SPEARDEMO
    ENDSCREEN11PIC,
    ENDSCREEN12PIC,
    ENDSCREEN3PIC,
    ENDSCREEN4PIC,
    ENDSCREEN5PIC,
    ENDSCREEN6PIC,
    ENDSCREEN7PIC,
    ENDSCREEN8PIC,
    ENDSCREEN9PIC,
#endif
    STATUSBARPIC,
    PG13PIC,
    CREDITSPIC,
#ifndef SPEARDEMO
    IDGUYS1PIC,
    IDGUYS2PIC,
    COPYPROTTOPPIC,
    COPYPROTBOXPIC,
    BOSSPIC1PIC,
    BOSSPIC2PIC,
    BOSSPIC3PIC,
    BOSSPIC4PIC,
#endif
    KNIFEPIC,
    GUNPIC,
    MACHINEGUNPIC,
    GATLINGGUNPIC,
    NOKEYPIC,
    GOLDKEYPIC,
    SILVERKEYPIC,
    N_BLANKPIC,
    N_0PIC,
    N_1PIC,
    N_2PIC,
    N_3PIC,
    N_4PIC,
    N_5PIC,
    N_6PIC,
    N_7PIC,
    N_8PIC,
    N_9PIC,
    FACE1APIC,
    FACE1BPIC,
    FACE1CPIC,
    FACE2APIC,
    FACE2BPIC,
    FACE2CPIC,
    FACE3APIC,
    FACE3BPIC,
    FACE3CPIC,
    FACE4APIC,
    FACE4BPIC,
    FACE4CPIC,
    FACE5APIC,
    FACE5BPIC,
    FACE5CPIC,
    FACE6APIC,
    FACE6BPIC,
    FACE6CPIC,
    FACE7APIC,
    FACE7BPIC,
    FACE7CPIC,
    FACE8APIC,
    GOTGATLINGPIC,
    GODMODEFACE1PIC,
    GODMODEFACE2PIC,
    GODMODEFACE3PIC,
    BJWAITING1PIC,
    BJWAITING2PIC,
    BJOUCHPIC,
    PAUSEDPIC,
    GETPSYCHEDPIC,

    STARTTILE8,
    TILE8 = STARTTILE8,

    STARTEXTERNS,
    ORDERSCREEN = STARTEXTERNS,
    ERRORSCREEN,

    STARTPALETTES,
    TITLEPALETTE = STARTPALETTES,
#ifndef SPEARDEMO
    END1PALETTE,
    END2PALETTE,
    END3PALETTE,
    END4PALETTE,
    END5PALETTE,
    END6PALETTE,
    END7PALETTE,
    END8PALETTE,
    END9PALETTE,
    IDGUYSPALETTE,
#endif
    STARTDEMOS,
    T_DEMO0 = STARTDEMOS,
#ifndef SPEARDEMO
    T_DEMO1,
    T_DEMO2,
    T_DEMO3,
#endif
    STARTENDTEXT,
#ifndef SPEARDEMO
    T_ENDART1 = STARTENDTEXT,
#endif
    NUMCHUNKS
};

//
// Amount of each data item
//
#define NUMFONT      (STARTPICS - STARTFONT)
#define NUMPICS      (STARTTILE8 - STARTPICS)
#define NUMTILE8     35
#define NUMEXTERNS   (NUMCHUNKS - STARTEXTERNS)
#define NUMPALETTES  (STARTDEMOS - STARTPALETTES)
#define NUMDEMOS     (STARTENDTEXT - STARTDEMOS)

//
// Thank you for using IGRAB!
//

#endif
