//////////////////////////////////////
//
// Graphics .H file for Apogee v1.4
// IGRAB-ed on Sun May 03 01:19:32 1992
//
//////////////////////////////////////

#ifndef __GFXV_APO_H_
#define __GFXV_APO_H_

enum graphicnums
{
    STRUCTPIC,

    STARTFONT,
    FONT1 = STARTFONT,
    FONT2,

    STARTPICS,
    H_BJPIC = STARTPICS,
    H_CASTLEPIC,
    H_KEYBOARDPIC,
    H_JOYPIC,
    H_HEALPIC,
    H_TREASUREPIC,
    H_GUNPIC,
    H_KEYPIC,
    H_BLAZEPIC,
    H_WEAPON1234PIC,
    H_WOLFLOGOPIC,
    H_VISAPIC,
    H_MCPIC,
    H_IDLOGOPIC,
    H_TOPWINDOWPIC,
    H_LEFTWINDOWPIC,
    H_RIGHTWINDOWPIC,
    H_BOTTOMINFOPIC,
#if !defined(APOGEE_1_0) && !defined(APOGEE_1_1) && !defined(APOGEE_1_2)
    H_SPEARADPIC,
#endif
    C_OPTIONSPIC,
    C_CURSOR1PIC,
    C_CURSOR2PIC,
    C_NOTSELECTEDPIC,
    C_SELECTEDPIC,
    C_FXTITLEPIC,
    C_DIGITITLEPIC,
    C_MUSICTITLEPIC,
    C_MOUSELBACKPIC,
    C_BABYMODEPIC,
    C_EASYPIC,
    C_NORMALPIC,
    C_HARDPIC,
    C_LOADSAVEDISKPIC,
    C_DISKLOADING1PIC,
    C_DISKLOADING2PIC,
    C_CONTROLPIC,
    C_CUSTOMIZEPIC,
    C_LOADGAMEPIC,
    C_SAVEGAMEPIC,
    C_EPISODE1PIC,
    C_EPISODE2PIC,
    C_EPISODE3PIC,
    C_EPISODE4PIC,
    C_EPISODE5PIC,
    C_EPISODE6PIC,
    C_CODEPIC,
#ifndef APOGEE_1_0
    C_TIMECODEPIC,
    C_LEVELPIC,
    C_NAMEPIC,
    C_SCOREPIC,
#if !defined(APOGEE_1_1) && !defined(APOGEE_1_2)
    C_JOY1PIC,
    C_JOY2PIC,
#endif
#else
    C_TIMECODEPIC = C_CODEPIC,
#endif
    L_GUYPIC,
    L_COLONPIC,
    L_NUM0PIC,
    L_NUM1PIC,
    L_NUM2PIC,
    L_NUM3PIC,
    L_NUM4PIC,
    L_NUM5PIC,
    L_NUM6PIC,
    L_NUM7PIC,
    L_NUM8PIC,
    L_NUM9PIC,
    L_PERCENTPIC,
    L_APIC,
    L_BPIC,
    L_CPIC,
    L_DPIC,
    L_EPIC,
    L_FPIC,
    L_GPIC,
    L_HPIC,
    L_IPIC,
    L_JPIC,
    L_KPIC,
    L_LPIC,
    L_MPIC,
    L_NPIC,
    L_OPIC,
    L_PPIC,
    L_QPIC,
    L_RPIC,
    L_SPIC,
    L_TPIC,
    L_UPIC,
    L_VPIC,
    L_WPIC,
    L_XPIC,
    L_YPIC,
    L_ZPIC,
    L_EXPOINTPIC,
#ifndef APOGEE_1_0
    L_APOSTROPHEPIC,
#endif
    L_GUY2PIC,
    L_BJWINSPIC,
    STATUSBARPIC,
    TITLEPIC,
    PG13PIC,
    CREDITSPIC,
    HIGHSCORESPIC,
    KNIFEPIC,
    GUNPIC,
    MACHINEGUNPIC,
    GATLINGGUNPIC,
    NOKEYPIC,
    GOLDKEYPIC,
    SILVERKEYPIC,
    N_BLANKPIC,
    N_0PIC,
    N_1PIC,
    N_2PIC,
    N_3PIC,
    N_4PIC,
    N_5PIC,
    N_6PIC,
    N_7PIC,
    N_8PIC,
    N_9PIC,
    FACE1APIC,
    FACE1BPIC,
    FACE1CPIC,
    FACE2APIC,
    FACE2BPIC,
    FACE2CPIC,
    FACE3APIC,
    FACE3BPIC,
    FACE3CPIC,
    FACE4APIC,
    FACE4BPIC,
    FACE4CPIC,
    FACE5APIC,
    FACE5BPIC,
    FACE5CPIC,
    FACE6APIC,
    FACE6BPIC,
    FACE6CPIC,
    FACE7APIC,
    FACE7BPIC,
    FACE7CPIC,
    FACE8APIC,
    GOTGATLINGPIC,
    MUTANTBJPIC,
    PAUSEDPIC,
    GETPSYCHEDPIC,

    STARTTILE8,
    TILE8 = STARTTILE8,

    STARTEXTERNS,
    ORDERSCREEN = STARTEXTERNS,
    ERRORSCREEN,

    STARTHELPTEXT,
    T_HELPART = STARTHELPTEXT,
#ifdef APOGEE_1_0
    STARTENDTEXT,
    T_ENDART1 = STARTENDTEXT,
#endif
    STARTDEMOS,
    T_DEMO0 = STARTDEMOS,
    T_DEMO1,
    T_DEMO2,
    T_DEMO3,
#ifndef APOGEE_1_0
    STARTENDTEXT,
    T_ENDART1 = STARTENDTEXT,
#ifndef UPLOAD
    T_ENDART2,
    T_ENDART3,
    T_ENDART4,
    T_ENDART5,
    T_ENDART6,
#endif
#endif
    NUMCHUNKS
};

//
// Amount of each data item
//
#define NUMFONT      (STARTPICS - STARTFONT)
#define NUMPICS      (STARTTILE8 - STARTPICS)
#define NUMTILE8     35
#define NUMEXTERNS   (NUMCHUNKS - STARTEXTERNS)
#ifdef APOGEE_1_0
    #define NUMDEMOS     (NUMCHUNKS - STARTDEMOS)
#else
    #define NUMDEMOS     (STARTENDTEXT - STARTDEMOS)
#endif

//
// Thank you for using IGRAB!
//

#endif
